### ISSUE TITLE
suggestions for lake/ocean solution?

### ISSUE THREAD

**Issue by jasonswearingen** [Tshmofen/waterways-net#5]
Your waterways looks perfect for flowing water, which to me was "the missing part" for water rendering in godot.   

There are a lot of general lake/ocean water solutions for godot, do you happen to have a suggestion of one to use with Waterways?   I am a C# dev and ideally I am focused on procedural asset placement.

**Comment by Tshmofen** [comment]
Lakes/oceans are pretty easy to implement anyway, don't think there is much need for a separate addon :). You just need to write/find (i.e. https://godotshaders.com/) nice shader for water and put it on the plane (subdivided for waves).

If you are going to use it for big procedural worlds, you can just determine some specific ocean height and move it along the height after the player (far ocean could be a LOD, maybe just color-matched plane). You also might need to update the shader to use global coordinates for noise, so that you would not notice it moving with you.

If you need to set up physics for it, it might be a bit harder, but simplest approach is to just copy shader vertex function in the code and use it to detemine actual height of the wave. And once you have a method to detemine height of the point in the water - it's pretty easy to affect any rigid bodies entering it. You can see an example in this test script: [FloatingCube.cs](https://github.com/Tshmofen/waterways-net/blob/main/TestAssets/Scripts/FloatingCube.cs) - `RiverFloatSystem` is being assigned by `Area3D` that monitors applicable objects that are close to the water.

Well, if you still want to try some addon - unfortunately can't help here, don't really know any, so you will have to try a few yourself and see if they work for you.

**Comment by jasonswearingen** [comment]
thank you so much for the reply, it gives great info.   I'm still pretty far from adding water but I think you are giving the starting points I need :)
